language: perl
perl:
  - "5.20"
  - "5.16"
  - "5.12"
env:
  - "HARNESS_OPTIONS=j4 TEST_ONLINE=1"
before_install:
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
  - echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list
  - sudo apt-get update -q
  - sudo apt-get install mongodb-org-server
install:
  - "cpanm -n Test::Pod Test::Pod::Coverage IO::Socket::SSL"
  - "cpanm -n --installdeps ."
notifications:
  email: false
